[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1


[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['denite.nvim']
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = ['denite.nvim']
on_path = '.*'


[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
    nmap <silent> <C-u><C-f> :<C-u>Denite file_rec<CR>
    nmap <silent> <C-u><C-l> :<C-u>Denite line<CR>
    nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
    nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
    nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
'''

hook_source = '''
    call denite#custom#source(
    \ 'file_mru', 'matchers', ['matcher_fuzzy', 'matcher_project_files'])

'''


