[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    set background=dark
    au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

